In [1]:
# import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model
import pandas as pd

In [2]:
def load_data(filename):
    cols=["N", "Time_in_us"]
    return pd.read_csv(filename, names=cols)

df = load_data('dev0_h2d_stepsize4.csv')
# df = load_data('dev1_h2d_stepsize4.csv')


X = df["N"]
y  = df["Time_in_us"]
    
X = np.array(X)
y = np.array(y)

X = X.reshape(-1,1)
y = y.reshape(-1,1)

In [3]:
lr_model = linear_model.LinearRegression()
lr_model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [4]:
print lr_model.coef_
print lr_model.intercept_

[[ 0.00062165]]
[ 1.8122791]


In [5]:
print "Mean squared error: %.6f" % np.mean((lr_model.predict(X) - y) ** 2)
print('Variance score: %.6f' % lr_model.score(X, y))

Mean squared error: 0.001865
Variance score: 0.999422


### testing

In [6]:
lr_model.predict(500)

array([[ 2.12310202]])

In [7]:
lr_model.predict(1000)

array([[ 2.43392495]])

In [8]:
lr_model.predict(500000)

array([[ 312.63520401]])

In [9]:
# 1m
lr_model.predict(1000000)

array([[ 623.45812893]])

In [10]:
# 10m
lr_model.predict(10000000)

array([[ 6218.27077739]])

In [11]:
# 100m
lr_model.predict(100000000)

array([[ 62166.39726203]])

### contention

In [12]:
lr_model.predict(409600)

array([[ 256.43841919]])

In [13]:
lr_model.predict(819200)

array([[ 511.06455928]])

### permutation

In [14]:
np.random.seed(42)

sample = np.random.choice(df.index, size= int(len(df) * 0.9), replace=False)

data, test_data = df.ix[sample], df.drop(sample)

In [15]:
X_train, y_train = data["N"], data["Time_in_us"]
X_test, y_test = test_data["N"], test_data["Time_in_us"]

X_train = X_train.reshape(-1,1)
y_train = y_train.reshape(-1,1)

X_test = X_train.reshape(-1,1)
y_test = y_train.reshape(-1,1)


lr_model.fit(X_train, y_train)

print lr_model.coef_
print lr_model.intercept_

[[ 0.0006215]]
[ 1.81329683]


/home/leiming/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:4: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
/home/leiming/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:5: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead


In [16]:
print "Mean squared error: %.6f" % np.mean((lr_model.predict(X_test) - y_test) ** 2)
print('Variance score: %.6f' % lr_model.score(X_test, y_test))

Mean squared error: 0.001904
Variance score: 0.999411
